#ESCRIBE UN PROGRAMA QUE SOLICITE AL USUARIO UN NUMERO ENTERO Y DETERMINE SI ES PAR O IMPAR

#VARIABLES

num1=int(input("INGRESA UN NUMERO: "))

#OPERADORES

if num1%2==0:
    print("EL NUMERO ES PAR")
else:
    print("EL NUMERO ES IMPAR")